name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.12.2'
      - name: Install Dependencies
        run: npm install
      - name: Build Application
        run: npm run build
        
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_PROUD_ROCK_018D89E03 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: "upload"
          app_location: "/" # App source code path
          api_location: "" # Api source code path - optional
          output_location: "build" # Built app content directory - optional
        env:
          REACT_APP_CLIENT_ID: ${{ secrets.REACT_APP_CLIENT_ID }}
          REACT_APP_STORAGE_ACCOUNT_NAME: ${{ secrets.REACT_APP_STORAGE_ACCOUNT_NAME }}
          REACT_APP_STORAGE_ACCOUNT_KEY: ${{ secrets.REACT_APP_STORAGE_ACCOUNT_KEY }}
          REACT_APP_SHARE_NAME: ${{ secrets.REACT_APP_SHARE_NAME }}
          REACT_APP_SUBSCRIPTION_ID: ${{ secrets.REACT_APP_SUBSCRIPTION_ID }}
          REACT_APP_AUTHORITY: ${{ secrets.REACT_APP_AUTHORITY }}
          REACT_APP_OBJ_ID: ${{ secrets.REACT_APP_OBJ_ID }}
          REACT_APP_SAS_TOKEN: ${{ secrets.REACT_APP_SAS_TOKEN }}
          REACT_APP_BASTION_URL: ${{ secrets.REACT_APP_BASTION_URL }}
          REACT_APP_TENANT_ID: ${{ secrets.REACT_APP_TENANT_ID }}
          REACT_APP_JWT_SECRET: ${{ secrets.REACT_APP_JWT_SECRET }}

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_PROUD_ROCK_018D89E03 }}
          action: "close"



